use_frameworks!

platform :ios, '9.0'

target 'AEObjCWorking_Example' do
  pod 'AEObjCWorking', :path => '../'
  pod 'Masonry', '~> 1.1.0'
  pod 'YYModel',      '~> 1.0.4'        #数据解析
  pod 'YYWebImage', '~> 1.0.5'
  pod 'SDWebImage', '~> 5.0'
  pod 'SDCycleScrollView','>= 1.82'
  pod 'CocoaAsyncSocket', '~> 7.6.5'
  pod 'SVProgressHUD', '~> 2.2.5'
  pod "CTMediator"
  pod 'Google-Mobile-Ads-SDK', '~> 8.13.0'

  target 'AEObjCWorking_Tests' do
    inherit! :search_paths

    #pod 'FBSnapshotTestCase'
  end
  
 post_install do |installer|
     installer.generated_projects.each do |project|
           project.targets.each do |target|
               target.build_configurations.each do |config|
                   config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
                end
           end
    end
 end
  

end
