use_frameworks!

platform :ios, '8.0'

target 'AEObjCWorking_Example' do
  pod 'AEObjCWorking', :path => '../'

  target 'AEObjCWorking_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
